In [3]:
import pandas as pd
import numpy as np

In [4]:
data = {
    "Temperatur Udara (°C)": [10, 25, 15, 20, 18, 20, 22, 24],
    "Kecepatan Angin (km/jam)": [0, 0, 5, 3, 7, 10, 5, 6],
    "Klasifikasi atau Persepsi Marry": ["Dingin", "Panas", "Dingin", "Panas", "Dingin", "Dingin", "Panas", "Panas"]
}

In [5]:
data_cuaca = pd.DataFrame(data)

In [6]:
data_cuaca

Temperatur Udara (°C)  Kecepatan Angin (km/jam)  \
0                     10                         0   
1                     25                         0   
2                     15                         5   
3                     20                         3   
4                     18                         7   
5                     20                        10   
6                     22                         5   
7                     24                         6   

  Klasifikasi atau Persepsi Marry  
0                          Dingin  
1                           Panas  
2                          Dingin  
3                           Panas  
4                          Dingin  
5                          Dingin  
6                           Panas  
7                           Panas

untuk perhitungan tugas ini akan dibuatkan fungsi python, tanpa menggunakan library dari sklearn

Berikut saya buatkan terlebih dahulu psqudocode atau urutan algorimtanya untuk membuat fungsinya
1. Pisahkan fitur-fitur data dengan menggunakan numpy, jadi akan ada dua array numpy
2. Kemudian kurangkan masing-masing array dengan data test yang didapat yaitu 16 derajat dan 3 km/jam
3. Hasil pengurangan ini akan menentukan kedekatan dari data
4. Tentukan nilai K, untuk memetakan data testing itu kemana, kemungkinan akan dibuatkan 3 nilai K, karena dengan nilai k=3 akan ada salah satu yang akan condong ke nilai tersebut antara panas dan dingin

In [7]:
data_cuaca['Temperatur Udara (°C)'].to_numpy(), data_cuaca['Kecepatan Angin (km/jam)'].to_numpy()

(array([10, 25, 15, 20, 18, 20, 22, 24]),
 array([ 0,  0,  5,  3,  7, 10,  5,  6]))

In [8]:
test_data = (16, 3)

In [9]:
(data_cuaca['Temperatur Udara (°C)'].to_numpy() - test_data[0]) + (data_cuaca['Kecepatan Angin (km/jam)'].to_numpy() - test_data[1])

array([-9,  6,  1,  4,  6, 11,  8, 11])

In [10]:
(data_cuaca['Temperatur Udara (°C)'].to_numpy() - test_data[0])**2 + (data_cuaca['Kecepatan Angin (km/jam)'].to_numpy() - test_data[1])**2

array([45, 90,  5, 16, 20, 65, 40, 73])

In [ ]:
def KNN_Algorthm(data, test_data, k=3):
    # mengubah kedalam numpy agar perhitungannya cepat 
    feature_1 = data['Temperatur Udara (°C)'].to_numpy()
    feature_2 = data['Kecepatan Angin (km/jam)'].to_numpy()

    jarak = (data['Temperatur Udara (°C)'].to_numpy() - test_data[0])**2 + (data['Kecepatan Angin (km/jam)'].to_numpy() - test_data[1])**2
    
    # kita urutkan nilai k
    target = data['Klasifikasi atau Persepsi Marry']
    
    # mencari index data berdasarkan index jarak yang telah disorting
    result = pd.DataFrame({'jarak' : jarak, 'target': target})

    return result.sort_values(by='jarak')[:k]


In [12]:
result = KNN_Algorthm(data_cuaca, test_data)
result


jarak  target
2      5  Dingin
3     16   Panas
4     20  Dingin

Dari perhitungan dengan function KNN_Algorthm dengan k atau nilai tetang yang diambil adalah 3, maka persepsi Marry untuk nilai data (16, 3) adalah Dingin